name: Web App
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /boxer_ayush/
